"use client"

import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

import { api } from "~/utils/api";

import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function MyApp({
  children,
  session,
}: {
  children: React.ReactNode
  session: Session | null
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}

export default api.withTRPC(MyApp);
